// void main() {
//   var setJurusan = <String>{};
//   setJurusan.add('AKL');
//   setJurusan.add('BDP');
//   setJurusan.add('OTKP');
//   setJurusan.add('RPL');
//   setJurusan.add('TKJ');
//   setJurusan.add('DG');
//   setJurusan.add('TBSM');
//   setJurusan.add('TPM');
//   setJurusan.add('TB');
//   setJurusan.add('TL');
//   print(setJurusan);
// }

// void main() {
//   var setJurusanAKL = <String>{};
//   var setJurusanBDP = <String>{};
//   var setJurusanOTKP = <String>{};
//   var setJurusanRPL = <String>{};
//   var setJurusanTKJ = <String>{};
//   var setJurusanDG = <String>{};
//   var setJurusanTBSM = <String>{};
//   var setJurusanTPM = <String>{};
//   var setJurusanTB = <String>{};
//   var setJurusanTL = <String>{};
//   setJurusanAKL.add('10 AKL 1');
//   setJurusanAKL.add('10 AKL 2');
//   setJurusanAKL.add('10 AKL 3');
//   setJurusanAKL.add('10 AKL 4');
//   setJurusanAKL.add('11 AKL 1');
//   setJurusanAKL.add('11 AKL 2');
//   setJurusanAKL.add('11 AKL 3');
//   setJurusanAKL.add('11 AKL 4');
//   setJurusanAKL.add('12 AKL 1');
//   setJurusanAKL.add('12 AKL 2');
//   setJurusanAKL.add('12 AKL 3');
//   setJurusanAKL.add('12 AKL 4');
//   setJurusanBDP.add('10 BR 1');
//   setJurusanBDP.add('10 BR 2');
//   setJurusanBDP.add('10 BR 3');
//   setJurusanBDP.add('10 BR 4');
//   setJurusanBDP.add('10 BD');
//   setJurusanOTKP.add('10 MP 1');
//   setJurusanOTKP.add('10 MP 2');
//   setJurusanOTKP.add('10 MP 3');
//   setJurusanOTKP.add('10 MP 4');
//   setJurusanOTKP.add('11 OTKP 1');
//   setJurusanOTKP.add('11 OTKP 2');
//   setJurusanOTKP.add('11 OTKP 3');
//   setJurusanOTKP.add('11 OTKP 4');
//   setJurusanOTKP.add('12 OTKP 1');
//   setJurusanOTKP.add('12 OTKP 2');
//   setJurusanOTKP.add('12 OTKP 3');
//   setJurusanOTKP.add('12 OTKP 4');
//   setJurusanOTKP.add('12 OTKP 5');
//   setJurusanRPL.add('10 RPL 1');
//   setJurusanRPL.add('10 RPL 2');
//   setJurusanRPL.add('10 RPL 3');
//   setJurusanRPL.add('11 RPL 1');
//   setJurusanRPL.add('11 RPL 2');
//   setJurusanRPL.add('12 RPL 1');
//   setJurusanRPL.add('12 RPL 2');
//   setJurusanTKJ.add('10 TKJ 1');
//   setJurusanTKJ.add('10 TKJ 2');
//   setJurusanTKJ.add('10 TKJ 3');
//   setJurusanTKJ.add('11 TKJ 1');
//   setJurusanTKJ.add('11 TKJ 2');
//   setJurusanTKJ.add('12 TKJ 1');
//   setJurusanTKJ.add('12 TKJ 2');
//   setJurusanTBSM.add('10 TBSM 1');
//   setJurusanTBSM.add('10 TBSM 2');
//   setJurusanTBSM.add('10 TBSM 3');
//   setJurusanTBSM.add('10 TBSM 4');
//   setJurusanTBSM.add('11 TBSM 1');
//   setJurusanTBSM.add('11 TBSM 2');
//   setJurusanTBSM.add('12 TBSM 1');
//   setJurusanTBSM.add('12 TBSM 2');
//   setJurusanTPM.add('10 TPM 1');
//   setJurusanTPM.add('10 TPM 2');
//   setJurusanTPM.add('10 TPM 3');
//   setJurusanTPM.add('11 TPM 1');
//   setJurusanTPM.add('11 TPM 2');
//   setJurusanTPM.add('12 TPM 1');
//   setJurusanTPM.add('12 TPM 2');
//   setJurusanDG.add('10 DG 1');
//   setJurusanDG.add('10 DG 2');
//   setJurusanDG.add('10 DG 3');
//   setJurusanDG.add('11 DG 1');
//   setJurusanDG.add('11 DG 2');
//   setJurusanDG.add('12 DG');
//   setJurusanTB.add('10 TB 1');
//   setJurusanTB.add('10 TB 2');
//   setJurusanTB.add('10 TB 3');
//   setJurusanTB.add('11 TB 1');
//   setJurusanTL.add('10 TL 1');
//   setJurusanTL.add('10 TL 2');
//   setJurusanTL.add('10 TL 3');
//   setJurusanTL.add('11 TL');
//   setJurusanAKL.remove('11 AKL 1');
//   setJurusanAKL.remove('11 AKL 2');
//   setJurusanAKL.remove('11 AKL 3');
//   setJurusanAKL.remove('11 AKL 4');
//   setJurusanBDP.remove('11 BDP 1');
//   setJurusanBDP.remove('11 BDP 2');
//   setJurusanBDP.remove('11 BDP 3');
//   setJurusanBDP.remove('11 BDP 4');
//   setJurusanBDP.remove('11 BDP 5');
//   setJurusanOTKP.remove('11 OTKP 1');
//   setJurusanRPL.remove('11 RPL 1');
//   setJurusanTKJ.remove('11 TKJ 1');
//   setJurusanTKJ.remove('11 TKJ 1');
  

//  print('Jurusan AKL');
//  print(setJurusanAKL );
//  print('\n');
//  print('Jurusan BDP');
//  print(setJurusanBDP);
//  print('\n');
//  print('Jurusan OTKP');
//  print(setJurusanOTKP);
//  print('\n');
//  print('Jurusan RPL');
//  print(setJurusanRPL);
//  print('\n');
//  print('Jurusan TKJ');
//  print(setJurusanTKJ);
//  print('\n');
//  print('Jurusan TBSM');
//  print(setJurusanTBSM);
//  print('\n');
//  print('Jurusan TPM');
//  print(setJurusanTPM);
//  print('\n');
//  print('Jurusan DG');
//  print(setJurusanDG);
//  print('\n');
//  print('Jurusan TB');
//  print(setJurusanTB);
//  print('\n');
//  print('Jurusan TL');
//  print(setJurusanTL);
// }




// void main() {
//   var setJurusan = <String>{};
//   setJurusan.add('AKL');
//   setJurusan.add('BDP');
//   setJurusan.add('OTKP');
//   setJurusan.add('RPL');
//   setJurusan.add('TKJ');
//   setJurusan.add('TBSM');
//   setJurusan.add('TPM');
//   setJurusan.add('TB');
//   setJurusan.add('TL');
//   print(setJurusan);
// }




void main() {
  var setJurusanAKL = <String>{};
  var setJurusanBDP = <String>{};
  var setJurusanOTKP = <String>{};
  var setJurusanRPL = <String>{};
  var setJurusanTKJ = <String>{};
  var setJurusanTBSM = <String>{};
  var setJurusanTPM = <String>{};
  var setJurusanDG = <String>{};
  var setJurusanTB = <String>{};
  var setJurusanTL = <String>{};
  setJurusanAKL.add('10 AKL 1');
  setJurusanAKL.add('10 AKL 2');
  setJurusanAKL.add('10 AKL 3');
  setJurusanAKL.add('10 AKL 4');
  setJurusanAKL.add('11 AKL 1');
  setJurusanAKL.add('11 AKL 2');
  setJurusanAKL.add('11 AKL 3');
  setJurusanAKL.add('11 AKL 4');
  setJurusanAKL.add('12 AKL 1');
  setJurusanAKL.add('12 AKL 2');
  setJurusanAKL.add('12 AKL 3');
  setJurusanAKL.add('12 AKL 4');
  setJurusanBDP.add('10 BR 1');
  setJurusanBDP.add('10 BR 2');
  setJurusanBDP.add('10 BR 3');
  setJurusanBDP.add('10 BR 4');
  setJurusanBDP.add('10 BD');
  setJurusanBDP.add('11 BDP 1');
  setJurusanBDP.add('11 BDP 2');
  setJurusanBDP.add('11 BDP 3');
  setJurusanBDP.add('11 BDP 4');
  setJurusanBDP.add('11 BDP 5');
  setJurusanBDP.add('12 BDP 1');
  setJurusanBDP.add('12 BDP 2');
  setJurusanBDP.add('12 BDP 3');
  setJurusanBDP.add('12 BDP 4');
  setJurusanOTKP.add('10 MP 1');
  setJurusanOTKP.add('10 MP 2');
  setJurusanOTKP.add('10 MP 3');
  setJurusanOTKP.add('10 MP 4');
  setJurusanOTKP.add('11 OTKP 1');
  setJurusanOTKP.add('11 OTKP 2');
  setJurusanOTKP.add('11 OTKP 3');
  setJurusanOTKP.add('11 OTKP 4');
  setJurusanOTKP.add('12 OTKP 1');
  setJurusanOTKP.add('12 OTKP 2');
  setJurusanOTKP.add('12 OTKP 3');
  setJurusanOTKP.add('12 OTKP 4');
  setJurusanOTKP.add('12 OTKP 5');
  setJurusanRPL.add('10 RPL 1');
  setJurusanRPL.add('10 RPL 2');
  setJurusanRPL.add('10 RPL 3');
  setJurusanRPL.add('11 RPL 1');
  setJurusanRPL.add('11 RPL 2');
  setJurusanRPL.add('12 RPL 1');
  setJurusanRPL.add('12 RPL 2');
  setJurusanTKJ.add('10 TKJ 1');
  setJurusanTKJ.add('10 TKJ 2');
  setJurusanTKJ.add('10 TKJ 3');
  setJurusanTKJ.add('11 TKJ 1');
  setJurusanTKJ.add('11 TKJ 2');
  setJurusanTKJ.add('12 TKJ 1');
  setJurusanTKJ.add('12 TKJ 2');
  setJurusanTBSM.add('10 TBSM 1');
  setJurusanTBSM.add('10 TBSM 2');
  setJurusanTBSM.add('10 TBSM 3');
  setJurusanTBSM.add('10 TBSM 4');
  setJurusanTBSM.add('11 TBSM 1');
  setJurusanTBSM.add('11 TBSM 2');
  setJurusanTBSM.add('12 TBSM 1');
  setJurusanTBSM.add('12 TBSM 2');
  setJurusanTPM.add('10 TPM 1');
  setJurusanTPM.add('10 TPM 2');
  setJurusanTPM.add('10 TPM 3');
  setJurusanTPM.add('11 TPM 1');
  setJurusanTPM.add('11 TPM 2');
  setJurusanTPM.add('12 TPM 1');
  setJurusanTPM.add('12 TPM 2');
  setJurusanDG.add('10 DG 1');
  setJurusanDG.add('10 DG 2');
  setJurusanDG.add('10 DG 3');
  setJurusanDG.add('11 DG 1');
  setJurusanDG.add('11 DG 2');
  setJurusanDG.add('12 DG');
  setJurusanTB.add('10 TB 1');
  setJurusanTB.add('10 TB 2');
  setJurusanTB.add('10 TB 3');
  setJurusanTB.add('11 TB 1');
  setJurusanTL.add('10 TL 1');
  setJurusanTL.add('10 TL 2');
  setJurusanTL.add('10 TL 3');
  setJurusanTL.add('11 TL');
  setJurusanRPL.addAll(setJurusanTKJ);
  setJurusanRPL.addAll(setJurusanTBSM);
  setJurusanRPL.addAll(setJurusanTPM);
  setJurusanRPL.addAll(setJurusanDG);
  setJurusanRPL.addAll(setJurusanTB);
  setJurusanRPL.addAll(setJurusanTL);
  setJurusanOTKP.addAll(setJurusanBDP);
  setJurusanOTKP.addAll(setJurusanAKL);
 



 print('\n');
 print('Jurusan Bisnis');
 print(setJurusanOTKP);
 print('\n');
 print('Jurusan Teknik');
 print(setJurusanRPL);

}